---
- hosts: all
  become: true
  become_user: root
  become_method: su

  vars_files:
    - vars/main.yml

  handlers:
    - name: Include handlers
      import_tasks: tasks/handlers.yml

  tasks:
    - import_tasks: tasks/main.yml
      when: ansible_distribution == 'OpenBSD'
