---
- hosts: all
  become: true
  become_user: root
  become_method: su

  roles:
   - login_conf
   - group
   - doas
   - sysctl
   - firmware
   - syspatch
   - sshd
   - packages
   - xfce
   - openbox
   - rcctl
   - obsdfreqd
   - reboot
