---
  - name: Load vars
    include_vars: vars/main.yml

  - include_tasks: tasks/login_conf.yml
  - include_tasks: tasks/groups.yml
  - include_tasks: tasks/doas.yml
  - include_tasks: tasks/sysctl.yml
  - include_tasks: tasks/firmware.yml
  - include_tasks: tasks/syspatch.yml
  - include_tasks: tasks/sshd.yml
  - include_tasks: tasks/upgrade.yml
  - include_tasks: tasks/packages.yml
  - include_tasks: tasks/xfce.yml
  - include_tasks: tasks/openbox.yml
  - include_tasks: tasks/rcctl.yml
  - include_tasks: tasks/xenodm.yml
  - include_tasks: tasks/reboot.yml