---
- name: Altering login.conf
  copy: 
    src: login.conf
    dest: /etc/login.conf
    owner: root
    group: wheel
    mode: '0644'

- name: Generating DB
  shell: cap_mkdb /etc/login.conf

- name: Adding "{{ user_name }}" to staff login class
  shell: usermod -L staff "{{ user_name }}"